package com.ek.basic.model.pojo;
// Generated 2017-7-13 19:27:21 by Hibernate Tools 3.5.0.Final

import java.util.Date;

/**
 * UserInfo generated by hbm2java
 */
@SuppressWarnings("serial")
public class UserInfo implements java.io.Serializable {

	private Integer uuid;
	private String userName;
	private Date birthday;
	private String sex;

	public UserInfo() {
	}

	public UserInfo(String userName, Date birthday, String sex) {
		this.userName = userName;
		this.birthday = birthday;
		this.sex = sex;
	}

	public Integer getUuid() {
		return this.uuid;
	}

	public void setUuid(Integer uuid) {
		this.uuid = uuid;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

}
